Added missing comment
Added missing comment, this is required to add in MainActivity.java, otherwise throwing an error /MainActivity.java:28: error: cannot find symbol
        SendSMSPackage.getInstance().onActivityResult(requestCode, resultCode, data);
        ^
  symbol:   variable SendSMSPackage
  location: class MainActivity
1 error